openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts web servise
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Contacts
    description: Operations with contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-1-fa7k.onrender.com
paths:
  /students:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/students/post.yaml'
  /students/{id}:
    get:
      $ref: '../swagger/paths/students/{id}/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer